"""lib/holdings.py — Phase 6C-A holdings persistence (local JSON only).

This module is the **single** read/write boundary for the user's manually-entered
portfolio positions on the Trading Desk page (``pages/9_Trading_Desk.py``).

Design rules / guardrails (Phase 6C-A):

* **Local JSON only.** Holdings are persisted to ``data/holdings.json`` (the
  ``data/`` directory is created on first write if absent). There is NO database,
  NO vector store, and NO external persistence service.
* **Fail-closed.** Every read/write is wrapped in ``try/except`` and degrades
  gracefully: :func:`load_holdings` returns ``[]`` on a missing/corrupt file and
  :func:`save_holdings` returns ``False`` on any write failure. No function in
  this module raises to the page.
* **Review-only.** A :class:`HoldingRecord` is a record of what the user *says*
  they hold for thesis tracking — it carries NO broker / order / execution
  capability, no order ticket, no ``approved_for_execution`` field, and produces
  no buy/sell instruction.

A :class:`HoldingRecord` is a plain dataclass; the page never writes
``holdings.json`` directly — all access goes through the functions below.
"""

from __future__ import annotations

import json
import os
import uuid
from dataclasses import asdict as _dc_asdict, dataclass, field, fields as _dc_fields
from pathlib import Path
from typing import Optional

# data/holdings.json lives under the repo-root data/ directory. Computed once
# from this file's location so it is independent of the process working dir.
_REPO_ROOT = Path(__file__).resolve().parent.parent
_DATA_DIR = _REPO_ROOT / "data"
HOLDINGS_PATH = _DATA_DIR / "holdings.json"

# Documented vocabularies (validated softly — an unexpected value is preserved
# rather than raising, keeping the module fail-closed).
HORIZON_VALUES = ("short", "mid", "long")
THESIS_SOURCE_VALUES = ("manual", "cockpit", "scanner")
STATUS_VALUES = ("active", "closed")


@dataclass
class HoldingRecord:
    """One manually-entered portfolio position with its tracked thesis.

    ``id`` is a uuid4 hex string generated on creation when not supplied (so a
    record round-tripped from JSON keeps its original id). ``thesis_signals``
    inherits the ``key_signals`` of the originating :class:`CandidateSignal` when
    ``thesis_source`` is ``"cockpit"`` / ``"scanner"``; it is empty for manual
    entries. Review-only: no execution field.
    """

    ticker: str = ""
    shares: float = 0.0
    cost_basis: float = 0.0  # per share
    entry_date: str = ""  # YYYY-MM-DD
    horizon: str = "mid"  # "short" | "mid" | "long"
    thesis_text: str = ""  # free text, editable
    thesis_source: str = "manual"  # "manual" | "cockpit" | "scanner"
    thesis_signals: list = field(default_factory=list)  # inherited key_signals
    status: str = "active"  # "active" | "closed"
    closed_date: Optional[str] = None
    closed_price: Optional[float] = None
    notes: str = ""
    id: str = ""  # uuid4 hex; auto-generated when empty

    def __post_init__(self) -> None:
        if not self.id:
            self.id = uuid.uuid4().hex


@dataclass
class PortfolioSettings:
    """User-configurable, persisted portfolio-level risk settings (Entry v4).

    These drive the Existing Position Risk Overlay in ``lib/order_advisor.py``
    (position-size limit + horizon-specific risk-to-stop budgets). ``long_stop``
    is a fixed label ("thesis_break") because the LONG horizon never stops on a
    short-term technical move — it exits only on thesis break / valuation / a
    fundamental deterioration. Persisted to ``data/holdings.json`` under the
    top-level ``"portfolio_settings"`` key; review-only (no execution field).
    """

    max_position_pct: float = 0.15      # single-name cap as a fraction of total assets
    short_max_loss_pct: float = 0.02    # SHORT add risk-to-stop budget (of total assets)
    mid_max_loss_pct: float = 0.05      # MID add risk-to-stop budget (of total assets)
    long_stop: str = "thesis_break"     # fixed label — LONG stop is thesis-driven


# ---------------------------------------------------------------------------
# (De)serialization helpers
# ---------------------------------------------------------------------------

_FIELD_NAMES = {f.name for f in _dc_fields(HoldingRecord)}
_SETTINGS_FIELD_NAMES = {f.name for f in _dc_fields(PortfolioSettings)}


def holding_to_dict(record: "HoldingRecord") -> dict:
    """Return a plain JSON-serializable dict for one HoldingRecord."""
    return {name: getattr(record, name) for name in _FIELD_NAMES}


def holding_from_dict(data: dict) -> "HoldingRecord":
    """Build a HoldingRecord from a dict, ignoring unknown keys (fail-closed).

    Missing keys fall back to the dataclass defaults; an absent/empty ``id`` is
    regenerated by ``__post_init__``.
    """
    safe = {k: v for k, v in (data or {}).items() if k in _FIELD_NAMES}
    rec = HoldingRecord(**safe)
    # Normalize list/None typed fields defensively.
    if not isinstance(rec.thesis_signals, list):
        rec.thesis_signals = []
    return rec


# ---------------------------------------------------------------------------
# Public read / write API (all fail-closed)
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# On-disk format
# ---------------------------------------------------------------------------
# data/holdings.json is a TOP-LEVEL OBJECT: ``{"holdings": [...],
# "cash_position": <float>}``. The holdings list and the cash position live side
# by side. For backward compatibility a bare JSON list (the pre-cash format) is
# still read as ``{"holdings": <list>, "cash_position": 0.0}`` and is migrated to
# the object form on the next write. Everything is fail-closed.


def _read_json_raw():
    """Read + parse ``data/holdings.json`` (raw JSON), or ``None`` (fail-closed)."""
    try:
        if not HOLDINGS_PATH.is_file():
            return None
        with open(HOLDINGS_PATH, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except Exception:  # noqa: BLE001 — fail-closed (missing / corrupt file)
        return None


def _split_raw(raw) -> tuple:
    """Normalize raw JSON to ``(holdings_list_of_dicts, cash_position_float)``."""
    if isinstance(raw, list):
        return raw, 0.0
    if isinstance(raw, dict):
        items = raw.get("holdings", [])
        items = items if isinstance(items, list) else []
        try:
            cash = float(raw.get("cash_position", 0.0) or 0.0)
        except (TypeError, ValueError):
            cash = 0.0
        return items, cash
    return [], 0.0


def _read_settings(raw) -> Optional[dict]:
    """Return the raw ``portfolio_settings`` sub-dict, or ``None`` (fail-closed)."""
    if isinstance(raw, dict):
        ps = raw.get("portfolio_settings")
        if isinstance(ps, dict):
            return ps
    return None


def _write_raw(holdings_payload: list, cash_position: float,
               settings_payload: Optional[dict] = None) -> bool:
    """Atomically write the ``{"holdings", "cash_position", "portfolio_settings"}``
    object (fail-closed).

    When ``settings_payload`` is ``None`` the existing on-disk
    ``portfolio_settings`` block is PRESERVED (read back before the overwrite) so
    a holdings- or cash-only write never drops the user's saved settings.
    """
    try:
        _DATA_DIR.mkdir(parents=True, exist_ok=True)
        try:
            cash = float(cash_position or 0.0)
        except (TypeError, ValueError):
            cash = 0.0
        payload = {"holdings": list(holdings_payload or []), "cash_position": cash}
        if settings_payload is None:
            # Preserve any existing settings block across a holdings/cash write.
            existing = _read_settings(_read_json_raw())
            if existing is not None:
                payload["portfolio_settings"] = existing
        else:
            payload["portfolio_settings"] = settings_payload
        tmp = HOLDINGS_PATH.with_suffix(".json.tmp")
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, ensure_ascii=False, indent=2)
        os.replace(tmp, HOLDINGS_PATH)
        return True
    except Exception:  # noqa: BLE001 — fail-closed write
        return False


def load_holdings() -> list:
    """Return all persisted :class:`HoldingRecord`s.

    Reads ``data/holdings.json`` (object or legacy-list form). Returns ``[]`` when
    the file is absent, empty, not valid JSON, or malformed — never raises.
    """
    try:
        raw = _read_json_raw()
        if raw is None:
            return []
        items, _ = _split_raw(raw)
        out: list = []
        for item in items:
            if isinstance(item, dict):
                try:
                    out.append(holding_from_dict(item))
                except Exception:  # noqa: BLE001 — skip one bad record, keep going
                    continue
        return out
    except Exception:  # noqa: BLE001 — fail-closed (missing / corrupt file)
        return []


def save_holdings(holdings: list) -> bool:
    """Persist ``holdings`` to ``data/holdings.json`` atomically-ish.

    Preserves the existing ``cash_position`` (see :func:`save_cash_position`).
    Creates the ``data/`` directory if absent. Returns ``True`` on success and
    ``False`` on ANY failure (never raises). Writes to a temp file then replaces
    so a crash mid-write cannot truncate the existing file.
    """
    try:
        payload = []
        for h in (holdings or []):
            if isinstance(h, HoldingRecord):
                payload.append(holding_to_dict(h))
            elif isinstance(h, dict):
                payload.append(holding_to_dict(holding_from_dict(h)))
        # Preserve the existing cash position across a holdings rewrite.
        cash = load_cash_position()
        return _write_raw(payload, cash)
    except Exception:  # noqa: BLE001 — fail-closed write
        return False


def load_cash_position() -> float:
    """Return the persisted cash position (top-level field), or ``0.0`` (fail-closed)."""
    try:
        raw = _read_json_raw()
        if raw is None:
            return 0.0
        _, cash = _split_raw(raw)
        return cash
    except Exception:  # noqa: BLE001 — fail-closed
        return 0.0


def save_cash_position(amount: float) -> bool:
    """Persist the cash position (top-level field), preserving holdings (fail-closed)."""
    try:
        raw = _read_json_raw()
        items, _ = _split_raw(raw) if raw is not None else ([], 0.0)
        return _write_raw(items, amount)
    except Exception:  # noqa: BLE001 — fail-closed write
        return False


def load_portfolio_settings() -> "PortfolioSettings":
    """Return the persisted :class:`PortfolioSettings` (top-level
    ``portfolio_settings`` key), or the defaults when absent / corrupt (fail-closed)."""
    try:
        ps = _read_settings(_read_json_raw())
        if not isinstance(ps, dict):
            return PortfolioSettings()
        safe = {k: v for k, v in ps.items() if k in _SETTINGS_FIELD_NAMES}
        return PortfolioSettings(**safe)
    except Exception:  # noqa: BLE001 — fail-closed
        return PortfolioSettings()


def save_portfolio_settings(settings: "PortfolioSettings") -> bool:
    """Persist ``settings`` to the top-level ``portfolio_settings`` key.

    Preserves the holdings list and cash position. Returns ``True`` on success and
    ``False`` on ANY failure (never raises).
    """
    try:
        if not isinstance(settings, PortfolioSettings):
            return False
        raw = _read_json_raw()
        items, cash = _split_raw(raw) if raw is not None else ([], 0.0)
        return _write_raw(items, cash, settings_payload=_dc_asdict(settings))
    except Exception:  # noqa: BLE001 — fail-closed write
        return False


def add_holding(record: "HoldingRecord") -> bool:
    """Append one HoldingRecord and persist. Returns ``False`` on failure."""
    try:
        if not isinstance(record, HoldingRecord):
            record = holding_from_dict(record)
        holdings = load_holdings()
        holdings.append(record)
        return save_holdings(holdings)
    except Exception:  # noqa: BLE001 — fail-closed
        return False


def update_holding(id: str, updates: dict) -> bool:
    """Partially update the record with ``id``.

    Only fields present in ``updates`` (and valid HoldingRecord fields) are
    changed; ``id`` itself is never overwritten. Returns ``False`` if the id is
    not found or persistence fails (never raises).
    """
    try:
        if not id or not isinstance(updates, dict):
            return False
        holdings = load_holdings()
        found = False
        for rec in holdings:
            if rec.id == id:
                for k, v in updates.items():
                    if k in _FIELD_NAMES and k != "id":
                        setattr(rec, k, v)
                found = True
                break
        if not found:
            return False
        return save_holdings(holdings)
    except Exception:  # noqa: BLE001 — fail-closed
        return False


def close_holding(id: str, closed_price: float, closed_date: str) -> bool:
    """Mark the holding ``id`` closed with the given exit price + date.

    Sets ``status="closed"``, ``closed_price``, and ``closed_date``. Returns
    ``False`` if the id is not found or persistence fails (never raises). This is
    a bookkeeping state change only — it places no order and executes nothing.
    """
    try:
        return update_holding(
            id,
            {
                "status": "closed",
                "closed_price": float(closed_price) if closed_price is not None else None,
                "closed_date": closed_date,
            },
        )
    except Exception:  # noqa: BLE001 — fail-closed
        return False


def get_active_holdings() -> list:
    """Return only the holdings whose ``status`` is ``"active"`` (fail-closed)."""
    try:
        return [h for h in load_holdings() if getattr(h, "status", "active") == "active"]
    except Exception:  # noqa: BLE001 — fail-closed
        return []
